name: Upgrade Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruby Upgrade Action
        uses: andrew/ruby-upgrade-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}